version: '3.8'

services:
  app:
    image: node:18-alpine
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3500
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install --silent || true && npm run dev"
    # Mapeo de puerto para desarrollo (exponer 3500)
    ports:
      - "3500:3500"
    networks:
      - red-web

networks:
  red-web:
    external: true
